-- Phase: agentic clinician assistant.
-- Stores LLM-generated daily/shift-handover briefs + on-demand summaries.
-- Read-only from the agent's perspective: only the brief_scheduler and the
-- on-demand /api/agent/brief endpoint INSERT here.

CREATE TABLE IF NOT EXISTS public.agent_briefs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          text NOT NULL CHECK (kind IN ('shift_handover', 'on_demand')),
    content       text NOT NULL,
    metadata      jsonb,
    generated_at  timestamptz NOT NULL DEFAULT now(),
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS agent_briefs_generated_at_idx
    ON public.agent_briefs (generated_at DESC);
